name: Publish new version of Indicatieregister

on:
  workflow_dispatch:
  push:
    branches:
      - Indicatieregister-*
    # paths:
    #   - 'gql-specificaties/**'

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate version
        id: version
        run: |
          BRANCH_NAME="${GITHUB_REF_NAME//\//-}"
          VERSION="${BRANCH_NAME}-$(date +'%Y.%m.%d.%H%M%S')"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v.${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          files: gql-specificatie/Indicatieregister.graphql
          generate_release_notes: true
          body: |
            Automatisch gegenereerde release van de Koppelvlakspecificatie voor branch `${{ github.ref_name }}`.
            Version: ${{ steps.version.outputs.version }}.
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
